// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace RadzenDh5.DHModels
{
    [Table("GROUP_WRT")]
    public partial class GroupWrt
    {
        [Key]
        [Column("GROUP_ID")]
        [StringLength(10)]
        public string GroupId { get; set; }
        [Key]
        [Column("PROG_ID")]
        [StringLength(10)]
        public string ProgId { get; set; }
        [Required]
        [Column("QUERY_WRT")]
        [StringLength(1)]
        public string QueryWrt { get; set; }
        [Required]
        [Column("PRINT_WRT")]
        [StringLength(1)]
        public string PrintWrt { get; set; }
        [Required]
        [Column("IMPORT_WRT")]
        [StringLength(1)]
        public string ImportWrt { get; set; }
        [Required]
        [Column("EXPORT_WRT")]
        [StringLength(1)]
        public string ExportWrt { get; set; }
        [Required]
        [Column("UPDATE_WRT")]
        [StringLength(1)]
        public string UpdateWrt { get; set; }
        [Required]
        [Column("DELETE_WRT")]
        [StringLength(1)]
        public string DeleteWrt { get; set; }
        [Required]
        [Column("APPROVE_WRT")]
        [StringLength(1)]
        public string ApproveWrt { get; set; }
        [Required]
        [Column("ENABLE")]
        [StringLength(1)]
        public string Enable { get; set; }
        [Column("REMARK")]
        public string Remark { get; set; }
        [Required]
        [Column("TRN_USER")]
        [StringLength(50)]
        public string TrnUser { get; set; }
        [Required]
        [Column("TRN_DATE")]
        [StringLength(20)]
        public string TrnDate { get; set; }
        [Required]
        [Column("CRT_USER")]
        [StringLength(50)]
        public string CrtUser { get; set; }
        [Required]
        [Column("CRT_DATE")]
        [StringLength(20)]
        public string CrtDate { get; set; }
    }
}