// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace RadzenDh5.DHModels
{
    [Table("USER_MST")]
    public partial class UserMst
    {
        [Key]
        [Column("USER_ID")]
        [StringLength(20)]
        public string UserId { get; set; }
        [Column("DEPT_NAME")]
        [StringLength(50)]
        public string DeptName { get; set; }
        [Required]
        [Column("USER_NAME")]
        [StringLength(50)]
        public string UserName { get; set; }
        [Required]
        [Column("USER_PSWD")]
        [StringLength(50)]
        public string UserPswd { get; set; }
        [Column("TELPHONE")]
        [StringLength(50)]
        public string Telphone { get; set; }
        [Column("MOBILE")]
        [StringLength(50)]
        public string Mobile { get; set; }
        [Column("EMAIL")]
        [StringLength(50)]
        public string Email { get; set; }
        [Required]
        [Column("LANGUAGE")]
        [StringLength(2)]
        public string Language { get; set; }
        [Required]
        [Column("ENABLE")]
        [StringLength(1)]
        public string Enable { get; set; }
        [Column("REMARK")]
        public string Remark { get; set; }
        [Required]
        [Column("TRN_USER")]
        [StringLength(50)]
        public string TrnUser { get; set; }
        [Required]
        [Column("TRN_DATE")]
        [StringLength(20)]
        public string TrnDate { get; set; }
        [Required]
        [Column("CRT_USER")]
        [StringLength(50)]
        public string CrtUser { get; set; }
        [Required]
        [Column("CRT_DATE")]
        [StringLength(20)]
        public string CrtDate { get; set; }
        [Column("PSWD_DATE")]
        [StringLength(20)]
        public string PswdDate { get; set; }
        [Column("LAST_DATE")]
        [StringLength(20)]
        public string LastDate { get; set; }
    }
}