// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace RadzenDh5.DHModels
{
    [Keyless]
    public partial class VUserRole
    {
        [Required]
        [StringLength(450)]
        public string UserId { get; set; }
        [StringLength(256)]
        public string UserName { get; set; }
        [Required]
        [StringLength(450)]
        public string RoleId { get; set; }
        [StringLength(256)]
        public string RoleName { get; set; }
    }
}